/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tutorial;

/**
 *
 * @author User
 */
import java.util.*;

public class T1{
	public static void main(String[] args){

		Scanner s = new Scanner(System.in);
		Random r = new Random();

		System.out.println("Choose question number");

		int choice = s.nextInt();

		switch(choice){

//Question 1. Request two numbers from the user and print the multiplication of the numbers
			case 1:

				System.out.println("Enter num1:");
				int num1 = s.nextInt();

				System.out.println("Enter num2:");
				int num2 = s.nextInt();

				int multi = num1 * num2;

				System.out.println("The multiplication is " + multi);

			break;

//Question 2. Determine whether a random number is greater than 50.
			case 2:

				int randnum = 1 + r.nextInt(100);

				if (randnum > 50){
					System.out.println(randnum + " is greater than 50.");
				}

				else{
					System.out.println(randnum + " is smaller than 50.");
				}

			break;

//Question 3. Print the pass/fail grade based on the mark entered by user. The passing mark is at
//            least 40.
			
			case 3:

				System.out.println("Enter your mark: ");

				int mark = s.nextInt();

				if (mark >= 40 && mark <= 100){
					System.out.println("Pass");
				}

				else if (mark <40 && mark >= 0){
					System.out.println("Fail");

				}

			break;


//Question 4. Print the results of the two players’ dice game. 

			case 4:

				int p1 = 1 + r.nextInt(6);
				int p2 = 1 + r.nextInt(6);

				if (p1 > p2){
					System.out.println("p1 wins");
				}
				else if (p2 > p1){
					System.out.println("p2 wins");
				}
				else if (p1 == p2){
					System.out.println("Tie");
				}

			break;

//Question 5. Print the perimeter of a rectangle.

			case 5:
				
				System.out.println("Enter length: ");
				double l = s.nextDouble();
				System.out.println("Enter width: ");
				double w = s.nextDouble();

				double perimeter = 2 * (l + w);
				System.out.printf("Perimeter is %.2f\n", perimeter);

			break;

//Question 6. Print the minimum number from 10 random numbers generated by computer

			case 6:

				int min = r.nextInt(100);
				int num;

				for (int counter = 0; counter < 9; counter++){
					num = 1 + r.nextInt(100);

					int shownum = counter + 1;

					System.out.println("num" + "[" + shownum + "]" + " is " + num);

					if (num < min){
						min = num;
					}

					/*
					else if (min <= num){
						min = min;
					}
					*/
				}
				System.out.println("The min num is " + min);

			break;

//Question 7. Print the number of odd and even number from 10 random numbers generated by
//            computer. The random number must be from 10 – 100.

			case 7:

				List<Integer> oddnum = new ArrayList<Integer>();
				List<Integer> evenum = new ArrayList<Integer>();

				int c = 0;
				while(c < 10){

					int randomnum = 10 + r.nextInt(91);

					System.out.println(randomnum);

					if(randomnum >= 10 && randomnum <= 100){

						if (randomnum % 2 == 0){
							evenum.add(randomnum);
						}
						else{
							oddnum.add(randomnum);
						}

						c++;
					}
				}

				System.out.println("The odd numbers are " + oddnum);

				System.out.println("The even numbers are " + evenum);

			break;

//QEUSTION 8. Count the number of alphabet U and M from a sentence entered by user
			
			case 8:

				Scanner sc = new Scanner(System.in);

				System.out.println("Enter a string to find freq of letter U & M:");

				String sen = sc.nextLine();
                                
                                String temp8;
                                
				int numOfU = 0;
				int numOfM = 0;
				int othernum = 0;
                                int u = 0;
                                int m = 0;

				for(int count = 0; count < sen.length(); count++){
				    
                                    // First way
                                    temp8 = sen.substring(count, count +1);
                                    
                                    if(temp8.contains("u") || temp8.contains("U")){
                                        u++;
                                    }else if(temp8.contains("m") || temp8.contains("M")){
                                        m++;
                                    }
                                    
                                    // Second way
                                    switch(sen.charAt(count)){
                                        case 'u':
                                        case 'U':
                                            numOfU++;
                                            break;
                                        
                                        case 'm':
                                        case 'M':
                                            numOfM++;
                                            break;
                                            
                                        default:
                                            othernum++;
                                    }
				}

                System.out.printf("Number of U: %d\nNumber of M: %d\nNumber of other letters: %d\n", numOfU, numOfM, othernum);
                System.out.printf("Number of U: %d\nNumber of M: %d\nNumber of other letters: %d\n", u, m, othernum);

                        break;

//QUESTION 9. Display the frequency of a keyword from a web page.
			case 9:
				
				Scanner sca = new Scanner(System.in);

				System.out.println("Enter the sentence: ");

				String sentence = sca.nextLine();

				String[] words = sentence.split("\\W+");

				System.out.println("Enter the word you want to count the frequency: ");

				String wordToCount = sca.nextLine();

				List<String> wordList = new ArrayList<String>();

				int wordFreq = 0;

				for(int a = 0; a < words.length; a++){

					wordList.add(a, words[a]);

				}

				for(int b = 0; b < words.length; b++){

					if(wordToCount.equals(words[b])){

						wordFreq++;

					}

				}

				System.out.printf("\nThe sentence is: \"%s\"", sentence);

				System.out.printf("\nThe number of words consist in this sentence: %d", words.length);

				System.out.printf("\nThe number of word \"%s\" consist in this sentence: %d\n", wordToCount, wordFreq);


			break;


//QUESTION 10. Display the number of female student from a random list of 100 students.

			case 10:
			
				Random ran = new Random();
	
				List<String> gender = new ArrayList<String>();

				gender.add("Male");

				gender.add("Female");

				int female = 0;

				int male = 0;

				for(int i = 0; i < 100; i++){

					String showgen = gender.get(ran.nextInt(2));

					System.out.println(showgen);

					switch(showgen){

						case "Female":

							female++;

						break;

						default:

							male++;
					}
				}
	
				System.out.printf("The number of female student is %d while the number of male student is %d.\n", female, male);

			break;

//QUESTION 11. Display a list of 5 random numbers in descending order. (Sort)

			case 11:

				System.out.println("Enter the number of elements you want: ");

				int n = s.nextInt();

				int temp;

				//List<Integer> randNumList = new ArrayList<Integer>();

				int randNumList[] = new int[n];			// or int[] list = new int[size]; also can

				for(int i = 0; i < n; i++){

					//randNumList.add(i, 1 + r.nextInt(100));
					randNumList[i] = 1 + r.nextInt(100);    // <--  FOR int randNumList[] = new int[n];

				}

				System.out.print("The random number list is: [");
				
				for(int i = 0; i < n - 1; i++){

					System.out.print(randNumList[i] + ", ");

				}

					System.out.println(randNumList[n-1] + "]");

				//System.out.println(randNumList.get(0)); <-- FOR List<Integer> randNumList = new ArrayList<Integer>();
				//System.out.println(randNumList[0]);     <-- FOR int randNumList[] = new int[n];

				//ASCENDING ORDER

				for(int i = 0; i < n; i++){
					for(int j = i + 1; j < n; j++){
						
						if(randNumList[i] > randNumList[j]){

							temp = randNumList[i];
							randNumList[i] = randNumList[j];
							randNumList[j] = temp;

						}
					}
				}

				System.out.print("The number in ascending order: [");
				
				for(int k = 0; k < n-1; k++){

					System.out.print(randNumList[k] + ", ");

				}

				System.out.print(randNumList[n-1] + "]\n");


				//DESCENDING ORDER

				for(int i = 0; i < n; i++){
					for(int j = i + 1; j < n; j++){
						
						if(randNumList[i] < randNumList[j]){

							temp = randNumList[i];
							randNumList[i] = randNumList[j];
							randNumList[j] = temp;

						}
					}
				}

				System.out.print("The number in descending order: [");
				
				for(int k = 0; k < n-1; k++){

					System.out.print(randNumList[k] + ", ");

				}

				System.out.print(randNumList[n-1] + "]\n");

			break;

//QUESTION 12. Guess a random number generated by computer.

			case 12:
				Random rand = new Random();

				int comnum = 1 + rand.nextInt(3);

				System.out.println("Guess a number between 1 - 3");

				int guess = s.nextInt();

				if (guess == comnum){
					System.out.println("Correct");
				}
				else{
					System.out.println("Wrong");
				}
			
			break;

// DEFAULT
			default:
				main(args);

			}
		System.out.println("1 to restart: ");
		int endchoice = s.nextInt();
		if (endchoice == 1){
			main(args);
		}
		else{
			System.out.println("All updated on 26 September 2019 @ 8.29a.m.");
		}
	}
}